use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::{AppError, Result};

const GENERATED_MARKER: &str = "# Generated by Singularity Engine. Do not edit by hand.";
const MANIFEST: &str = concat!(
    "# Generated by Singularity Engine. Do not edit by hand.\n",
    "version: 1\n",
    "workspace:\n",
    "  generated: true\n",
);

const WORKSPACE_DIRS: &[&str] = &[
    "agents",
    "skills",
    "rules",
    "memory/facts",
    "memory/preferences",
    "memory/failures",
    "evals/datasets",
    "evals/graders",
    "evals/suites",
    ".singularity/worktrees",
    ".singularity/runs",
    ".singularity/cache",
    ".singularity/installs",
];

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InitializedWorkspace {
    pub root: PathBuf,
    pub manifest_path: PathBuf,
    pub store_path: PathBuf,
}

pub fn initialize(path: impl AsRef<Path>) -> Result<InitializedWorkspace> {
    let root = path.as_ref();
    create_dir(root)?;
    write_manifest(root)?;

    for relative in WORKSPACE_DIRS {
        create_dir(&root.join(relative))?;
    }

    let store_path = root.join(".singularity/repo.git");
    initialize_bare_repo(&store_path)?;

    Ok(InitializedWorkspace {
        root: root.to_path_buf(),
        manifest_path: root.join("singularity.yaml"),
        store_path,
    })
}

pub(crate) fn required_workspace_dirs() -> &'static [&'static str] {
    WORKSPACE_DIRS
}

fn write_manifest(root: &Path) -> Result<()> {
    let manifest_path = root.join("singularity.yaml");
    if manifest_path.exists() {
        let content = fs::read_to_string(&manifest_path).map_err(|source| AppError::Io {
            path: manifest_path.clone(),
            source,
        })?;
        if content.starts_with(GENERATED_MARKER) {
            return Ok(());
        }

        return Err(AppError::NonGeneratedManifest {
            path: manifest_path,
        });
    }

    fs::write(&manifest_path, MANIFEST).map_err(|source| AppError::Io {
        path: manifest_path,
        source,
    })
}

fn initialize_bare_repo(store_path: &Path) -> Result<()> {
    if store_path.join("HEAD").is_file() {
        return Ok(());
    }

    if let Some(parent) = store_path.parent() {
        create_dir(parent)?;
    }

    let output = Command::new("git")
        .arg("init")
        .arg("--bare")
        .arg(store_path)
        .output()
        .map_err(|source| AppError::Io {
            path: store_path.to_path_buf(),
            source,
        })?;

    if output.status.success() {
        return Ok(());
    }

    let stderr = String::from_utf8_lossy(&output.stderr).trim().to_owned();
    let stdout = String::from_utf8_lossy(&output.stdout).trim().to_owned();
    let message = if stderr.is_empty() { stdout } else { stderr };

    Err(AppError::StoreInit {
        path: store_path.to_path_buf(),
        message,
    })
}

fn create_dir(path: &Path) -> Result<()> {
    fs::create_dir_all(path).map_err(|source| AppError::Io {
        path: path.to_path_buf(),
        source,
    })
}
